### ISSUE TITLE
Coalesce Related Events

### ISSUE THREAD

**Issue by dwlehman** [cathay4t/peripety#2]
One potentially important factor for the user experience is coalescing related events. Example: Suppose you have your `/home` filesystem on an LVM logical volume (say it's called `lv_home`) with `sdb` as the physical volume. If there is an I/O error while lvm is trying to access the physical volume, at least three events would be generated:

1. SCSI I/O error for `sdb`
2. device-mapper I/O error on `lv_home`
3. filesystem error for `/home`

Getting three separate event notifications for one actual event is not a good experience for the user. It would be ideal if peripety would provide a way to combine these events in such a way as to make it easier for the user to learn what has happened and what the consequences are.

This could make use of an extension of the device-relations API we are hoping SID will provide. I'm wondering if that API might eventually be able to tell you which devices are using a given disk sector, a given virtual block within a dm device, or which file is associated with a given filesystem block or range of blocks. This is substantially more involved than merely reporting which devices are built on top of each other.

**Comment by cathay4t** [comment]
Just some notes about kernel status on this:

There will no error from device-mapper layer, only from buffer I/O layer(whether block number is incorrect) and SCSI layer.
And SCSI layer does not report hardware sector error, just print out the sense data(where these is no sector count).

**Comment by dwlehman** [comment]
I think we agreed that this should be left to some higher-level component. Please reopen if I am mistaken.
