### ISSUE TITLE
"Rust is memory-leak-proof" is not true

### ISSUE THREAD

**Issue by cuviper** [cathay4t/peripety#4]
Hi -- I'm happy to see another Rust project from Red Hat!

I just want to point out that the statement in the FAQ about being memory-leak-proof is not true.  Rust has great features for memory safety, in that references never outlive the referred object, and mutable references never alias.  However, leaks are explicitly allowed -- e.g. `Rc`/`Arc` cycles are possible, and `mem::forget` is a safe function!

For more information, see:
- https://doc.rust-lang.org/nomicon/leaking.html
- http://huonw.github.io/blog/2016/04/memory-leaks-are-memory-safe/

**Comment by cathay4t** [comment]
Thanks for mentioning that. The FFI also could leak memory. I will update the README file for this soon

**Comment by cathay4t** [comment]
Fixed in https://github.com/cathay4t/peripety/commit/334ad270a3a8b504bd326851ff0a37e9a776d862
